name: remote-action-test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: guilhermevale/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
